### ISSUE TITLE
Question banner fix: (1) back navigation (Problems Page) should have `hover` animation (2) exam's name doesn't show

### ISSUE THREAD

**Issue by Johnny850807** [Judge-Girl/Judge-Girl-Web#50]
(1) the back navigation (Problems Page) should have `hover` animation (turn into shadowing)
 it should have shadow during the mouse hovering on it

(2) exam's name doesn't show
![image](https://user-images.githubusercontent.com/23109467/115951264-622c5900-a512-11eb-88a7-477ec49d6d07.png)

**Comment by edisonhello** [comment]
@Johnny850807 Can you provide how to provide this bug?
In my local environment, I can't reproduce the bug.

![image](https://user-images.githubusercontent.com/15229692/115998130-73f82400-a618-11eb-896e-bdec6fae9220.png)

**Comment by edisonhello** [comment]
Also, I think `drop-shadow` can not have transition.
I don't know which one should I use: 
1. `box-shadow` with animation.
2. `drop-shadow` without animation.
3. Only use `text-shadow` (the left-pointed arrow will not have effect)

**Comment by Johnny850807** [comment]
> @Johnny850807 Can you provide how to provide this bug?
> In my local environment, I can't reproduce the bug.
> 
> ![image](https://user-images.githubusercontent.com/15229692/115998130-73f82400-a618-11eb-896e-bdec6fae9220.png)

Please try it on the beta environment

**Comment by Johnny850807** [comment]
> Also, I think `drop-shadow` can not have transition (according to some results I found.)
> I don't know which one should I use:
> 
> 1. `box-shadow` with animation.
> 2. `drop-shadow` without animation.
> 3. Only use `text-shadow` (the left-pointed arrow will not have effect)

Pick the one that best fits to the UI spec

**Comment by edisonhello** [comment]
> > Also, I think `drop-shadow` can not have transition (according to some results I found.)
> > I don't know which one should I use:
> > 
> > 1. `box-shadow` with animation.
> > 2. `drop-shadow` without animation.
> > 3. Only use `text-shadow` (the left-pointed arrow will not have effect)
> 
> Pick the one that best fits to the UI spec

Ok, I will choose the second option.
