### ISSUE TITLE
Can't see judges and submitted codes in the submission page 

### ISSUE THREAD

**Issue by Johnny850807** [Judge-Girl/Judge-Girl-Web#51]
Reproduce: 
User: `chaoyu@gmail.com`
1. go to exam's submission page
![image](https://user-images.githubusercontent.com/23109467/116036220-f1637900-a698-11eb-85e5-06c7c5e37fce.png)

2. go to the first question (problemId=3) 
3. See submission page's and click view judges and view source code 

![image](https://user-images.githubusercontent.com/23109467/116035431-8ebdad80-a697-11eb-8001-e9b2ad72ec05.png)

Note: not only exam's submissions page, but also the normal submissions page

**Comment by edisonhello** [comment]
This is not implemented.
